### ISSUE TITLE
Reduce flicker of tokens

### ISSUE THREAD

**Issue by jasbanza** [jasbanza/osmosis-companion#22]
- [ ] tokens refresh every 5 minutes, and re-render entire table.
- [ ] token prices refresh every 5 seconds, and update existing table.

**Comment by c-michail** [comment]
1) Can you render by column with AJAX ?
2) Token images should be refresh when you open the extension only not when the window is active

Just throwing some ideas ...

**Comment by jasbanza** [comment]
@chmichael I'm about to tackle this one now. :) will do some ajax loading of it, as well as image caching (not sure why it isn't caching, but will check now). Another issue with the "flashing" has to do with the order in which I render... I'm first fetching the data, calling the render rows function, then sorting the row order. need to sort before rendering too... else it flashes with

**Comment by jasbanza** [comment]
Resolved. Will deploy with next version
