### ISSUE TITLE
No epoch timer in 0.39

### ISSUE THREAD

**Issue by c-michail** [jasbanza/osmosis-companion#30]
Hello,
  You removed the epoch timer in v0.39!
  
  Thank you

**Comment by jasbanza** [comment]
Hi, it's still there, didn't change. But it sleeps during epoch for about
20 minutes. Can you confirm if you have it now?

**Comment by c-michail** [comment]
Nope! There is no timer label on the icon!


![osmo-chrome](https://user-images.githubusercontent.com/13120950/159178042-dde1804b-1ddd-4826-8f25-6358dcde6008.jpg)

**Comment by jasbanza** [comment]
I'll ask the community telegram group chat, mine is fine! perhaps reinstall or disable+enable it so long....

**Comment by chmichael** [comment]
Ok reinstallation did the trick! Strange!

Closing the ticket! Thank you! :)

**Comment by c-michail** [comment]
Ok reinstallation did the trick! Strange!

Closing the ticket! Thank you! :)
